name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "17.x"
          cache: yarn

      - run: yarn

      - name: Lint
        run: yarn lint

      - name: Build
        run: yarn build

      - name: Copying files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: ${{ secrets.REMOTE_PORT }}
          key: ${{ secrets.SSH_KEY }}
          rm: true
          strip_components: 1
          source: "dist/*"
          target: ${{ secrets.REMOTE_DIR }}
